/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */



#include <stm32f407g.h>
#include <stm32f407g_gpio_driver.h>


void delay(void)
{
	for(uint32_t i=0; i < 5000; i++);
}



int main(void)
{

	GPIO_Handle_t LED_Toggle;
	GPIO_Handle_t Button;

	Button.pGPIOx = GPIOA;
	Button.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	Button.GPIO_PinConfig.GPIO_PinMode = 0;
	Button.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	Button.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	Button.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	Button.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_MODE_OUT;


	LED_Toggle.pGPIOx = GPIOD;
	LED_Toggle.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	LED_Toggle.GPIO_PinConfig.GPIO_PinMode = 1;
	LED_Toggle.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	LED_Toggle.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_NO_PUPD;
	LED_Toggle.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	LED_Toggle.GPIO_PinConfig.GPIO_PinAltFunMode = GPIO_MODE_OUT;

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&LED_Toggle);

	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_Init(&Button);


	while(1)
	{
		if(GPIO_ReadFromInputPin(GPIOA, 0) == 1)
		{
			delay();
			GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);

		}

	}



	for(;;);
}
